### ISSUE TITLE
White Gap while changing the images

### ISSUE THREAD

**Issue by WrathChaos** [hamedtaheri32/react-native-image-slider-box#1]
Hello,
Nice library and nice combine with snap-carousel :)
I would love to use this library on my production level project how ever there is a white gap while scrolling images. 
Here are the some examples : 
![Simulator Screen Shot - iPhone 8 Plus - 2019-04-21 at 14 32 21](https://user-images.githubusercontent.com/6813862/56469433-809e7c00-6442-11e9-831e-28fcd6b2fa91.png)
![Simulator Screen Shot - iPhone 8 Plus - 2019-04-21 at 14 32 15](https://user-images.githubusercontent.com/6813862/56469469-dffc8c00-6442-11e9-8a9c-589a7278dd8b.png)

Also, I have some **recommendations**;
- When I set circleLoop, it automatically changes the images how ever there is no animation while changes. It changes instantly.
- Another one is about the same part. I would like to change the duration of circleLoop. 

Also, sometimes even I set the circleLoop, it **did not** automatically change the images.
I hope it helps :) 
Thank you so much

**Comment by hamedtaheri32** [comment]
Hello friend,

It's my pleasure to get to know you like this library,
I will check these issues and try to solve them.

regards,

**Comment by hamedtaheri32** [comment]
This is not an issue, this library use pagination. the style and effect of pagination is page by page and show this gap for separate each page from each other.
